export const SET_LOCATION_LONG = "SET_LOCATION_LONG";
export const SET_LOCATION_LAT = "SET_LOCATION_LAT";

export const ADD_USER_ATTRACTION = "ADD_USER_ATTRACTION";
export const ERROR_USER_ATTRACTION = "ERROR_USER_ATTRACTION";
export const ADD_USER_HOTEL = "ADD_USER_HOTEL";
export const ERROR_USER_HOTEL = "ERROR_USER_HOTEL";
export const ADD_USER_RESTURANT = "ADD_USER_RESTURANT";
export const ERROR_USER_RESTURANT = "ERROR_USER_RESTURANT";